### ISSUE TITLE
Getting error [ TypeError: getRouteParams is not a function ] for @nuxtjs/pwa

### ISSUE THREAD

**Issue by camelG** [nuxt-community/pwa-module#147]
## nuxt.config.js
```js
  /*
   ** Nuxt.js modules
   */
  modules: [
    ['@nuxtjs/pwa', {
      icon: false
    }]
  ],
```
run command 
```bash
npm run dev
```
get error
```bash
> nuxt

i Preparing project for development                                                                                                                                                                          10:38:16
i Initial build may take a while                                                                                                                                                                             10:38:16

 FATAL  getRouteParams is not a function                                                                                                                                                                     10:38:16

  at ModuleContainer.addManifest (node_modules\@nuxtjs\manifest\index.js:18:38)
  at hook (node_modules\@nuxtjs\manifest\index.js:7:17)
  at ModuleContainer.nuxtManifest (node_modules\@nuxtjs\manifest\index.js:11:12)
  at Promise (node_modules\@nuxt\core\dist\core.js:172:30)
  at new Promise (<anonymous>)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:170:12)
  at ModuleContainer.requireModule (node_modules\@nuxt\core\dist\core.js:121:17)
  at module (node_modules\@nuxtjs\pwa\index.js:7:17)
  at promise.then (node_modules\@nuxtjs\pwa\index.js:1:146)
  at process._tickCallback (internal/process/next_tick.js:68:7)


   ╭─────────────────────────────────────────────────╮
   │                                                 │
   │   ✖ Nuxt Fatal Error                            │
   │                                                 │
   │   TypeError: getRouteParams is not a function   │
   │                                                 │
   ╰─────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c98">#c98</a>)</em></sub></div>

**Comment by kennydorion** [comment]
Same issue there...

**Comment by manniL** [comment]
@kennydorion feel free to file a correct bug report then.

**Comment by posva** [comment]
this problem went away for me after updating nuxt to the latest stable version

**Comment by wemod123** [comment]
Same for me, while I updated the nuxt to latest version, but still it happens!

**Comment by pi0** [comment]
@wemod123 Try cleaning up yarn.lock and node_modules. This may be a yarn failure

**Comment by wemod123** [comment]
@pi0 
I had a try your suggestion: remove yarn.lock, and node_modules, and install all modules with fresh repo.
But still same error happend as this issue title told.

I go through the install process strictly follow the guide here:  https://pwa.nuxtjs.org/setup.html

**Suggest repopen this issue.**

**Comment by manniL** [comment]
@wemod123 Please provide a reproduction @wemod123

**Comment by wemod123** [comment]
I just create a sample repo, please have a check:
https://github.com/wemod123/nuxt-pwa-sample

**Comment by Caaalabash** [comment]
same problem
nuxt version:  2.2.6 ~ 2.4.5
@nuxtjs/pwa version:  v3.0.0-beta.1 ~ v3.0.0-beta.10

**Comment by pi0** [comment]
The known edge case should not happen anymore with `3.0.0-beta.11`
