### ISSUE TITLE
Workbox strategies uncaught no-response

### ISSUE THREAD

**Issue by riso348** [nuxt-community/pwa-module#176]
### Version

[v3.0.0-beta.14](https://github.com/pwa-module/releases/tag/v3.0.0-beta.14)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

workbox-strategies.prod.js:1 
Uncaught (in promise) no-response: no-response :: [{"url":"https://XXXX/admin/advertisements/create"}]
    at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.1.1/workbox/workbox-strategies.prod.js:1:2145)
	
@	workbox-core.prod.js:1makeRequest	
@	workbox-strategies.prod.js:1

### What is expected ?

Caught error or page load at least

### What is actually happening?

The webpage at https://XXXX/admin/advertisements/create might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

### Additional comments?

I have this error at soma of my subpages while using PWA.
How can i help, or send you something more to prevent this error. When i try to refresh the page, there is a Chrome error ERR_FAILED

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c126">#c126</a>)</em></sub></div>

**Comment by Syrou** [comment]
Got the same thing happening in our code.

**Comment by AndrewBogdanovTSS** [comment]
Same thing here

**Comment by sts-ryan-holton** [comment]
Same problem, currently using `3.0.0-beta.16`

**Comment by MSkred** [comment]
Same problem, currently using 3.0.0-beta.16

**Comment by pi0** [comment]
This is not probably a bug related to PWA module but Workbox itself. Please provide a reproduction so at least we have a way to investigate more. `same here` is not a way to help to resolve, unfortunately.

Please note that if this error happening for making a request to 3rd party domain: https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests

**Comment by isaumya** [comment]
I am also facing the exact same issue on my project. Honestly, there is no way to reproduce this error. I test my site like crazy all the time. So, often I open my site on a chrome incognito window with the dev tools open and console or network tab opened and then I load my site. In this scenario, many times it loads without that error and some time in the console I have that error which is being thrown by `sw.js`. I mean if I go to the Application tab in the dev tools, select Service Worker from the left, I can see 1 red cross beside `sw.js` when I click on that it takes me to the console and show me that error.

The crazy thing is if I do a soft or hard refresh of that page, that error is no longer there and I have no idea when it will come back again. If you want I can share my site URL if that what you need.

**Comment by andrew-boyd** [comment]
We're seeing this issue too. A lighthouse audit of our site seems to trigger the error reliably. Lighthouse logs an error under "Best Practices" saying that errors were logged to the console.

url: `…workbox/workbox-strategies.prod.js` (cdn.jsdelivr.net)
description: `no-response: no-response :: [{"url":"https://www.wearebraid.com/"}] at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145)`

Our site is being hosted via now.sh and all content / file requests should be local (no 3rd-part CDN for images currently).

**Comment by phartikainen** [comment]
Same issue here, shows with Lighthouse audit

**Comment by dchernokur** [comment]
Error is consistently triggered by LightHouse in chrome devtools.
- Generate new nuxt project as SPA and with PWA module
- Deploy to now.sh with https://github.com/nuxt/now-builder added
- Run lighthouse audit and see the error in "Best Practices" report

**Comment by petrovnn** [comment]
Same problem 
![image](https://user-images.githubusercontent.com/1567284/72241106-011b9300-35f7-11ea-95d0-48968ec04c46.png)

![image](https://user-images.githubusercontent.com/1567284/72241332-a2a2e480-35f7-11ea-87c7-b21408c591d7.png)

**Comment by jbty** [comment]
I have the same issue :(

**Comment by jbty** [comment]
I'm not sure, but placing '@nuxtjs/pwa' at the end (the last index) of "modules" array in nuxt.config.js solved the problem for me.

can someone confirm?

**Comment by petrovnn** [comment]
@jbty 

It does not work for me :(

Even if you comment out the modules or put @nuxtjs/pwa in the first place.

But in the early stages of development, there was no error.

![image](https://user-images.githubusercontent.com/1567284/72676273-69a7bb80-3aa0-11ea-9d4c-3635bfdda94b.png)

**Comment by jbty** [comment]
@petrovnn it's strange, since i update this line it's worked for me. (
it seems that nuxt / pwa is not active in dev mode by default [see here](https://pwa.nuxtjs.org/modules/workbox.html#dev)), you use nuxt/pwa only on production mode (if dev option is false)

here is the list of the other manipulations that I made:

- Uninstall and delete app cache from windows
- Clear all browsing data from chrome
- Delete .nuxt, dist folder and sw.js and run " generate"

my config:
`
pwa: {
    workbox: {},
    meta: {
      theme_color: '#000000',
      lang: 'fr',
      ogHost: 'https://sdsedsgwewergwg.com/',
      nativeUI: true
    },
    icon: {},
    manifest: {
      name: 'coachjeremy.fr',
      lang: 'fr',
      display: 'standalone'
    }
  },
`

I hope it will help

I take this opportunity to say that it would be magic if there were more examples of using options in the documentation or even a complete tutorial

**Comment by ch99q** [comment]
Been getting the same error too when running trough Lighthouse in my browser.

So I trough it maybe was something with the way chrome runs the audit, and when I tried using https://web.dev/measure/

The problem seem to have disappeared.

**Comment by AndrewBogdanovTSS** [comment]
@ch99q it's caused by the fact that Chrome is cleaning the previous data before new audit so all your new users will get this error. You can test it yourself by clearing cache and hard resetting the page

**Comment by ch99q** [comment]
@AndrewBogdanovTSS I realized my answer was incorrect the second I pressed 'comment', it was more running away from the problem. You are completely correct and it should be fixed so the users don't experience the issue.

**Comment by kevinmarrec** [comment]
Easy Reproduction :
- Go on a website using PWA module (https://lichter.io, https://marrec.io)
- Clear site data (includes service workers)
- Go on website -> Works
- Go offline & refresh -> See error in console + unreachable website
- Go online & refresh -> Works
- Go offline & refresh -> Works

Note : If you refresh twice while being online, the issue won't show up when going offline

Google Lighthouse Audits has an `offline` check after an `online` one, that's why the audit faces this error too.

**Comment by qmolab** [comment]
I had the same issue, my SW.js file was stock and looked like so:

`importScripts('https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-sw.js')`

`// --------------------------------------------------`
`// Configure`
`// --------------------------------------------------`

`// Set workbox config`
`workbox.setConfig({`
  `"debug": false`
`})`

`// Start controlling any existing clients as soon as it activates`
`workbox.core.clientsClaim()`

`// Skip over the SW waiting lifecycle stage`
`workbox.core.skipWaiting()`

`workbox.precaching.cleanupOutdatedCaches()`

`// --------------------------------------------------`
`// Precaches`
`// --------------------------------------------------`

`// Precache assets`

`// --------------------------------------------------`
`// Runtime Caching`
`// --------------------------------------------------`

`// Register route handlers for runtimeCaching`
`workbox.routing.registerRoute(new RegExp('/_nuxt/'), new workbox.strategies.CacheFirst ({}), 'GET')`
`workbox.routing.registerRoute(new RegExp('/'), new workbox.strategies.NetworkFirst ({}), 'GET')`

I manually added the following to the bottom of the file:

`workbox.routing.setCatchHandler(({url, event, params}) => {// Inside your service worker code:`
`	const strategy = new workbox.strategies.NetworkFirst({networkTimeoutSeconds: 10});`
`	return strategy.handle({`
`	  request: new Request(url),`
`	});`

And it no longer throws an error, at the expense of double downloading the first page a *new* user gets when first visiting the website / after clearing browser data. If your pages aren't too large, than this may be effective, though it is definitely not satisfactory. It is interesting to note here that the [NetworkFirst workbox strategy](https://developers.google.com/web/tools/workbox/reference-docs/v3/workbox-strategies_NetworkFirst.mjs) does not throw errors. The [CacheFirst strategy](https://developers.google.com/web/tools/workbox/reference-docs/v4/workbox-strategies_CacheFirst.mjs), on the other hand, does throw an error when it cannot find the resource in either cache or the network, which makes me think there is a problem registering the regex routes, though that seems unreasonable. My page speed did not change when using this hack, so it is viable for me for the time being.

**Comment by sefrem** [comment]
Hey. I had the same error. Following this StackOverflow [response](https://stackoverflow.com/questions/59039433/workbox-cache-first-not-caching-properly/59040270#59040270), I changed the caching strategy from CacheFirst to StaleWhileRevalidate and now everything works fine. As it appears the problem is that CacheFirst strategy doesn't work with opaque responses.

**Comment by AndrewBogdanovTSS** [comment]
@sefrem could you provide an example of your nuxt.config.js? I can't find an option where caching strategy can be set

**Comment by sefrem** [comment]
@AndrewBogdanovTSS
I'm not using nuxt actually. I just change caching strategies i use in my service worker file sw.js.

**Comment by ninest** [comment]
Are there any fixes? I'm on `^3.0.0-0`, and sometimes I get the error sometimes I don't:

```
The FetchEvent for "https://mywebsite.com/" resulted in a network error response: the promise was rejected.

workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://mywebsite.com/"}]
    at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145)
```

When I do get the error, the PWA doesn't work at all (the service worker seems to have an error), and the website doesn't work offline

When I don't get the error, everything works fine, and the site loads offline around 75% of the time. I'm not able to reproduce this reliably.

**Comment by AndrewBogdanovTSS** [comment]
It would be great if someone could provide at least a workaround for this issue. Maybe caching strategy could help, but it seems there is no way to change it via module's settings or at least I didn't find anything regarding such option in the documentation

**Comment by neiromendez** [comment]
Hi all, I would like handle the workbox lifecycle to notify when an update is available, when a user is offline or a installation is available, using vue cli pwa is easy but with nuxt I don't find any about this.. If someone can help I'll appreciate it.

**Comment by AndrewBogdanovTSS** [comment]
@neiromendez use discord channel, this is not the place for such requests

**Comment by kevinmarrec** [comment]
Hi everyone, I'm getting you some some updates today :

From my new investigation, there are two different issues which leads to a common error. Both are distinct though.

## Error (giving back context)

![image](https://user-images.githubusercontent.com/25272043/84482677-6fdd4500-ac98-11ea-9355-b975d470acc6.png)


## Issue 1 : Lighthouse test failing

The first one is concerning Google Lighthouse, which has a test failing because of a console error during the test.

Good news: I found how to fix it., this is due to this line : https://github.com/nuxt-community/pwa-module/blob/dev/lib/workbox/templates/sw.js#L19.

All you need is to set `workbox.clientClaims` module option to `false`.

## Issue 2 : Offline may not be totally working

You can check my comment made in April : https://github.com/nuxt-community/pwa-module/issues/176#issuecomment-618314637

This is due to something related to offline strategy, for which I don't have a fix yey.

**Comment by AndrewBogdanovTSS** [comment]
@kevinmarrec I tried your suggestion - it made no effect on lighthouse - error is still here, lowering the score https://take.ms/ylVlv

**Comment by Kayoshi-dev** [comment]
Hello!

I'm facing the same problem, has anyone found a workaround?

**Comment by fisherspoons** [comment]
<img width="923" alt="Снимок экрана 2021-11-12 в 17 55 40" src="https://user-images.githubusercontent.com/54633510/141495900-164c8aba-2ba1-416f-b451-061bb101035b.png">

Can someone help fix the problem, errors appear sometimes. The version I am using
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.2.0/workbox-sw.js');

**Comment by fisherspoons** [comment]
and this trouble with strategy for images I think

<img width="447" alt="Снимок экрана 2021-11-12 в 18 39 44" src="https://user-images.githubusercontent.com/54633510/141502355-98abd722-8360-4e4f-8caf-5cb36952f73e.png">

**Comment by TapanDerasari** [comment]
> ### Easy Reproduction
> **1)** Go on a website using PWA module (https://lichter.io, https://marrec.io) **2)** Clear site data (includes service workers) **3)** Go on website -> Works **4)** Go offline & refresh -> See error in console + unreachable website **5)** Go online & refresh -> Works **6)** Go offline & refresh -> Works
> 
> **Note** : If you refresh twice while being online, the issue won't show up when going offline, which means the issue is related to Workbox Offline Strategy.

I tried the above solutions but the issue is still appears.

Does anyone found the solution?

**Comment by nishittops** [comment]
> > ### Easy Reproduction
> > **1)** Go on a website using PWA module (https://lichter.io, https://marrec.io) **2)** Clear site data (includes service workers) **3)** Go on website -> Works **4)** Go offline & refresh -> See error in console + unreachable website **5)** Go online & refresh -> Works **6)** Go offline & refresh -> Works
> > Note : If you refresh twice while being online, the issue won't show up when going offline, which means the issue is related to Workbox Offline Strategy.
> 
> I tried the solutions menioned above comments but the issue is still appears.
> 
> Does anyone found the solution/workaround?
> 
> @jeffposnick any idea or Am I misssing something ?
> 
> Thanks in advance.

I'm also facing the same issue. 

@TapanDerasari Did you find the solution for it?

@jeffposnick

**Comment by ziadsarour** [comment]
> 👋 from the Workbox project.
> 
> This issue was just brought to my attention, and there's honestly a _lot_ going on here. There are many reasons why you might see a logged message about `no-response` from Workbox—different root causes will all result in that log message. I wanted to break down a few common scenarios that, based on scanning through this thread, folks might be seeing. If you feel like you're bumping into something that isn't covered, and might be due to an issue with Workbox, feel free to report it in the [Workbox issue tracker](https://github.com/GoogleChrome/workbox/issues)—please include reproduction steps and a live URL!
> 
> Anyway, here's an explanation for some of what's been encountered in this thread. (This might be a repetition of some of the earlier explanations.)
> 
> * If you're using an extension like [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) or something similar, then check to see if your failed requests are due to the extension's URL matching rules. The [original post](https://github.com/nuxt-community/pwa-module/issues/176#issue-430909066) in this issue was for a failure to request `https://XXXX/admin/advertisements/create`, and that `/advertisements/` in the URL certainly makes me suspicious that an ad blocker is responsible. If an ad blocker prevents a network request from succeeding, there's not much Workbox could do about it—unless there's already a previously cached response from a time before the  ad blocker was installed, or unless you have "fallback" rules set up in Workbox to serve alternative content when a request fails.
> * If you're seeing scenarios like what's described in [this comment](https://github.com/nuxt-community/pwa-module/issues/176#issuecomment-618314637), then as pointed out elsewhere in the thread, it's due to how the [service worker lifecycle](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#clientsclaim) works, and calling  `clients.claim()` (or the [`workbox-core` wrapper](https://developers.google.com/web/tools/workbox/modules/workbox-core#skip_waiting_and_clients_claim)) will result in the service worker taking control of the open tab immediately after it activates. Without `clients.claim()`, the service worker won't control a tab until the next time you navigate away and return, so going offline immediately and reloading will result in a page load that isn't under control of the service worker.

Thanks to this comment, I have figured out what was causing my file ```use-cookie-consent``` to be blocked : the name. I've renamed my file to ```use-privacy``` and everything works !
