### ISSUE TITLE
It's not possible to not have workbox.setConfig in sw.js

### ISSUE THREAD

**Issue by Guito** [nuxt-community/pwa-module#268]
### Version

[v3.0.0-beta.19](https://github.com/pwa-module/releases/tag/v3.0.0-beta.19)

### Reproduction link

[https://jsfiddle.net/zcrtmdsx/1/](https://jsfiddle.net/zcrtmdsx/1/)

### Steps to reproduce

When using 
```
pwa: {
  workbox: {
            importScripts: ["background-sync.js"],
            dev: true,
            config: undefined
        }
}
```

The compilation crashes because config is undefined:
```
if (options.config.debug === undefined) {
    // Debug field is by default set to true for localhost domain which is not always ideal
    options.config.debug = options.dev || this.options.dev
  }
```

And it's the only way to not have it added:
```
<% if (options.config) {%>
// Set workbox config
workbox.setConfig(<%= JSON.stringify(options.config, null, 2) %>)
<% } %>
```

### What is expected ?

To be able to not have the setConfig in sw.js so we can use workbox in importScripts

### What is actually happening?

There is a compilation error:
```
 FATAL  Cannot read property 'debug' of undefined                                                                     12:50:35

  at ModuleContainer.getOptions (node_modules\@nuxtjs\pwa\lib\workbox\options.js:88:22)
  at nuxt.hook (node_modules\@nuxtjs\pwa\lib\workbox\module.js:9:32)
  at fn (node_modules\hable\lib\hookable.js:50:45)
  at promise.then.previous (node_modules\hable\lib\utils.js:15:67)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/pwa-module/issues/c200">#c200</a>)</em></sub></div>

**Comment by ChesterHub** [comment]
I have this error right now. Has this been fixed yet?

**Comment by valdeir2000** [comment]
> I have this error right now. Has this been fixed yet?

I was having the same problem when trying to "background sync". I resolved it as follows:

**nuxt.config.js**

```js
pwa: {
    workbox: {
      dev: true,
      offlineStrategy: 'StaleWhileRevalidate',
      runtimeCaching: [
        {
          urlPattern: 'https://cdn.com/.*',
        }
      ],
      cachingExtensions: [ /* importScripts causes failure */
        'static/bg-sw.js'
      ]
    }
  }
```

**Comment by valdeir2000** [comment]
> I have this error right now. Has this been fixed yet?

I was having the same problem when trying to "background sync". I resolved it as follows:

**nuxt.config.js**

```js
pwa: {
    workbox: {
      dev: true,
      offlineStrategy: 'StaleWhileRevalidate',
      runtimeCaching: [
        {
          urlPattern: 'https://cdn.com/.*',
        }
      ],
      workboxExtensions: [ /* importScripts causes failure */
        'static/bg-sw.js'
      ]
    }
  }
```
