### ISSUE TITLE
works with Nuxt 3

### ISSUE THREAD

**Issue by mitraecp** [nuxt-community/pwa-module#537]
Hello everyone, first of all I apologize for opening an issue (I didn't find an area to ask questions). I would like to know if this module works with nuxt 3. because when I try to import it in nuxt.config, I get an error.

**Comment by clinton9ice** [comment]
Error like this 
```
ERROR  Cannot restart nuxt:  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                    13:50:50
  at pwa (node_modules/@nuxtjs/pwa/dist/pwa.js:733:10)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6713:10)

```
I'm also having same issue and was hoping to see any result.

**Comment by keduardo2117** [comment]
I'm also interested in knowing if this module can work with Nuxt 3, so far I only see solutions or topics related to NuxtJS when searching online

**Comment by rahulkumarsingh73690** [comment]
This module is not supported

**Comment by kuroji-fusky** [comment]
@mitraecp I've scoured from what's currently available at this time, others found a solution for a _working_ but unofficial PWA module [here](https://github.com/kevinmarrec/nuxt-pwa-module) created by Kevin - and unfortunately, this is the only way to get a PWA up and running until Nuxt 3 has released a built-in PWA module.

From what I can gather, and from other issues pertaining to this repo, I believe this is going to be a native feature from Nuxt 3 and [will be migrating all the features from this repo](https://nuxt.com/docs/community/roadmap/#%EF%B8%8F-roadmap), however it's still being worked on and not suitable for production yet.

**Comment by suruaku** [comment]
There's also not only nuxt specific pwa solution by vite-pwa which can be integrated with nuxt.
https://vite-pwa-org.netlify.app/frameworks/nuxt.html

**Comment by rahulkumarsingh73690** [comment]
@suruaku Is this stable?

**Comment by suruaku** [comment]
Yes, it's the vite-pwa itself has been around for a few year. The Nuxt3 integration is relatively fresh (like Nuxt3 itself) and it's done by Nuxt core team member Daniel.

https://github.com/vite-pwa/nuxt

**Comment by BroJenuel** [comment]
have you tried to set ssr to false? since PWA should be SPA, I believe.

**Comment by SkyaTura** [comment]
The fact that this module does not support Nuxt 3 should be explicit on the WebSite/Docs to avoid time waste

**Comment by keduardo2117** [comment]
I believe this is the module we should use for Nuxt 3 projects
https://nuxt.com/modules/vite-pwa-nuxt
